export interface PageInfo {
    number: string
    label: string
    isFound: boolean
    imagePath?: string
}

export const pageInfoList: Record<string, PageInfo> = {
  "n/a": {
    number: "n/a",
    isFound: false,
    label: "Not from Manual",
  },
  ...Object.fromEntries(
    Array.from({ length: 56 }, (_, i) => {
      const num = i;
      return [
        num,
        {
          number: `${num}`,
          label: `Page ${num}`,
          isFound: false,
          imagePath: `/manual/page (${num+1}).jpg`,
        },
      ];
    })
  ),
  a1: {
    number: `a1`,
    label: `Action: Break Seal`,
    isFound: false,
    imagePath: `/action/break seal.jpg`,
  },
  a2: {
    number: `a2`,
    label: `Action: Buy Potion`,
    isFound: false,
    imagePath: `/action/buy potion.jpg`,
  },
  a3: {
    number: `a3`,
    label: `Action: Fight Statue`,
    isFound: false,
    imagePath: `/action/fight statue.jpg`,
  },
  a4: {
    number: `a4`,
    label: `Action: Here Lies Hero`,
    isFound: false,
    imagePath: `/action/here lies the hero.jpg`,
  },
  a5: {
    number: `a5`,
    label: `Action: Here Lies Hero`,
    isFound: false,
    imagePath: `/action/here lies the hero.jpg`,
  },
  a6: {
    number: `a6`,
    label: `Action: Offer`,
    isFound: false,
    imagePath: `/action/offer.jpg`,
  },
  a7: {
    number: `a7`,
    label: `Action: Open Door`,
    isFound: false,
    imagePath: `/action/offer.jpg`,
  },
  a8: {
    number: `a8`,
    label: `Pick Up: Key`,
    isFound: false,
    imagePath: `/action/pick up key.jpg`,
  },
  a9: {
    number: `a9`,
    label: `Pick Up: Knife`,
    isFound: false,
    imagePath: `/action/pick up knife.jpg`,
  },
  a10: {
    number: `a10`,
    label: `Pick Up: Magic Orb`,
    isFound: false,
    imagePath: `/action/pick up magic orb.jpg`,
  },
  a11: {
    number: `a11`,
    label: `Pick Up: Page`,
    isFound: false,
    imagePath: `/action/pick up page.jpg`,
  },
  a12: {
    number: `a12`,
    label: `Pick Up: Seal Key`,
    isFound: false,
    imagePath: `/action/pick up seal key.jpg`,
  },
  a13: {
    number: `a13`,
    label: `Pick Up: Seal`,
    isFound: false,
    imagePath: `/action/pick up seal.jpg`,
  },
  a14: {
    number: `a13`,
    label: `Pick Up: Sword`,
    isFound: false,
    imagePath: `/action/pick up sword.jpg`,
  },
  a15: {
    number: `a15`,
    label: `Pick Up: Wand`,
    isFound: false,
    imagePath: `/action/pick up wand.jpg`,
  },
  a16: {
    number: `a16`,
    label: `Sign: By Gate`,
    isFound: false,
    imagePath: `/action/sign by gate.jpg`,
  },
  a17: {
    number: `a17`,
    label: `Action: Statue in Sealed Room`,
    isFound: false,
    imagePath: `/action/statue in sealed room.jpg`,
  },
  a18: {
    number: `a18`,
    label: `Action: Weather Vane`,
    isFound: false,
    imagePath: `/action/weather vane.jpg`,
  },
  a19: {
    number: `a19`,
    label: `Action: Well 1`,
    isFound: false,
    imagePath: `/action/well 1.jpg`,
  },
  a20: {
    number: `a20`,
    label: `Action: Well 2`,
    isFound: false,
    imagePath: `/action/well 2.jpg`,
  },
  at1: {
    number: `at1`,
    label: `At: Beneath Eastern Vault`,
    isFound: false,
    imagePath: `/at/at beneath eastern vault.jpg`,
  },
  at2: {
    number: `at2`,
    label: `At: Beneath Well`,
    isFound: false,
    imagePath: `/at/at beneath the well.jpg`,
  },
  at3: {
    number: `at3`,
    label: `At: Cathedral`,
    isFound: false,
    imagePath: `/at/at cathedral.jpg`,
  },
  at4: {
    number: `at4`,
    label: `At: Dark Tomb`,
    isFound: false,
    imagePath: `/at/at dark tomb.jpg`,
  },
  at5: {
    number: `at5`,
    label: `At: East Bell Tower`,
    isFound: false,
    imagePath: `/at/at east bell tower.jpg`,
  },
  at6: {
    number: `at6`,
    label: `At: East Forest`,
    isFound: false,
    imagePath: `/at/at east forest.jpg`,
  },
  at7: {
    number: `at7`,
    label: `At: Frog's Domain`,
    isFound: false,
    imagePath: `/at/at frog domain.jpg`,
  },
  at8: {
    number: `at8`,
    label: `At: guardhouse 1`,
    isFound: false,
    imagePath: `/at/at guardhouse 1.jpg`,
  },
  at9: {
    number: `at9`,
    label: `At: guardhouse 2`,
    isFound: false,
    imagePath: `/at/at guardhouse 2.jpg`,
  },
  at10: {
    number: `at10`,
    label: `At: Hero's Grave`,
    isFound: false,
    imagePath: `/at/at heros grave.jpg`,
  },
  at11: {
    number: `at11`,
    label: `At: Inside Eastern Vault`,
    isFound: false,
    imagePath: `/at/at inside eastern vault.jpg`,
  },
  at12: {
    number: `at21`,
    label: `At: Lower Forest`,
    isFound: false,
    imagePath: `/at/at lower forest.jpg`,
  },
  at13: {
    number: `at31`,
    label: `At: Path To Hero's Grave`,
    isFound: false,
    imagePath: `/at/at path to heros grave.jpg`,
  },
  at14: {
    number: `at14`,
    label: `At: Purple Room`,
    isFound: false,
    imagePath: `/at/at purple room.jpg`,
  },
  at15: {
    number: `at15`,
    label: `At: The Quarry`,
    isFound: false,
    imagePath: `/at/at quarry.jpg`,
  },
  at16: {
    number: `at16`,
    label: `At: Shop`,
    isFound: false,
    imagePath: `/at/at shop.jpg`,
  },
  at17: {
    number: `at17`,
    label: `At: Teleport Hub`,
    isFound: false,
    imagePath: `/at/at teleport hub.jpg`,
  },
  at18: {
    number: `at18`,
    label: `At: Vault Shaft`,
    isFound: false,
    imagePath: `/at/at vault shaft.jpg`,
  },
  at19: {
    number: `at19`,
    label: `At: West Bell Tower`,
    isFound: false,
    imagePath: `/at/at west bell tower.jpg`,
  },
  at20: {
    number: `at20`,
    label: `At: West Garden`,
    isFound: false,
    imagePath: `/at/at west garden.jpg`,
  },
  g1: {
    number: `g1`,
    label: `Get: Berry`,
    isFound: false,
    imagePath: `/get/get berry.jpg`,
  },
  g2: {
    number: `g2`,
    label: `Get: Bomb`,
    isFound: false,
    imagePath: `/get/get bomb.jpg`,
  },
  g3: {
    number: `g3`,
    label: `Get: Card`,
    isFound: false,
    imagePath: `/get/get card.jpg`,
  },
  g4: {
    number: `g4`,
    label: `Get: Coin`,
    isFound: false,
    imagePath: `/get/get coin.jpg`,
  },
  g5: {
    number: `g5`,
    label: `Get: Doll`,
    isFound: false,
    imagePath: `/get/get doll.jpg`,
  },
  g6: {
    number: `g6`,
    label: `Get: Fire Bomb`,
    isFound: false,
    imagePath: `/get/get fire bomb.jpg`,
  },
  g7: {
    number: `g7`,
    label: `Get: Flower`,
    isFound: false,
    imagePath: `/get/get flower.jpg`,
  },
  g8: {
    number: `g8`,
    label: `Get: Fruit`,
    isFound: false,
    imagePath: `/get/get fruit.jpg`,
  },
  g9: {
    number: `g9`,
    label: `Get: Gas Mask`,
    isFound: false,
    imagePath: `/get/get gas mask.jpg`,
  },
  g10: {
    number: `g10`,
    label: `Get: Gun`,
    isFound: false,
    imagePath: `/get/get gun.jpg`,
  },
  g11: {
    number: `g11`,
    label: `Get: Ice Bomb`,
    isFound: false,
    imagePath: `/get/get ice bomb.jpg`,
  },
  g12: {
    number: `g12`,
    label: `Get: Key To Old House`,
    isFound: false,
    imagePath: `/get/get key old house.jpg`,
  },
  g13: {
    number: `g13`,
    label: `Get: Key`,
    isFound: false,
    imagePath: `/get/get key.jpg`,
  },
  g14: {
    number: `g14`,
    label: `Get: Knife`,
    isFound: false,
    imagePath: `/get/get knife combined.jpg`,
  },
  g15: {
    number: `g15`,
    label: `Get: Laurals`,
    isFound: false,
    imagePath: `/get/get laurals.jpg`,
  },
  g16: {
    number: `g16`,
    label: `Get: Leaf`,
    isFound: false,
    imagePath: `/get/get leaf.jpg`,
  },
  g17: {
    number: `g17`,
    label: `Get: Magic Orb`,
    isFound: false,
    imagePath: `/get/get magic orb.jpg`,
  },
  g18: {
    number: `g18`,
    label: `Get: Mushroom`,
    isFound: false,
    imagePath: `/get/get mushroom.jpg`,
  },
  g19: {
    number: `g19`,
    label: `Get: Pepper`,
    isFound: false,
    imagePath: `/get/get pepper.jpg`,
  },
  g20: {
    number: `g20`,
    label: `Get: Piggy Bank`,
    isFound: false,
    imagePath: `/get/get piggy bank.jpg`,
  },
  g21: {
    number: `g21`,
    label: `Get: Potion Shard`,
    isFound: false,
    imagePath: `/get/get potion shard.jpg`,
  },
  g22: {
    number: `g22`,
    label: `Get: Potion`,
    isFound: false,
    imagePath: `/get/get potion.jpg`,
  },
  g23: {
    number: `g23`,
    label: `Get: Powder`,
    isFound: false,
    imagePath: `/get/get powder.jpg`,
  },
  g24: {
    number: `g24`,
    label: `Get: Seal Key`,
    isFound: false,
    imagePath: `/get/get seal key.jpg`,
  },
  g25: {
    number: `g25`,
    label: `Get: Seal`,
    isFound: false,
    imagePath: `/get/get seal.jpg`,
  },
  g26: {
    number: `g26`,
    label: `Get: Shield`,
    isFound: false,
    imagePath: `/get/get shield.jpg`,
  },
  g27: {
    number: `g27`,
    label: `Get: Statue`,
    isFound: false,
    imagePath: `/get/get statue.jpg`,
  },
  g28: {
    number: `g28`,
    label: `Get: Stick`,
    isFound: false,
    imagePath: `/get/get stick.jpg`,
  },
  g29: {
    number: `g29`,
    label: `Get: Sword`,
    isFound: false,
    imagePath: `/get/get sword.jpg`,
  },
  g30: {
    number: `g30`,
    label: `Get: Tooth`,
    isFound: false,
    imagePath: `/get/get tooth.jpg`,
  },
  g31: {
    number: `g31`,
    label: `Get: Wand`,
    isFound: false,
    imagePath: `/get/get wand.jpg`,
  },
  o1: {
    number: `o1`,
    label: `Other: Above Gate`,
    isFound: false,
    imagePath: `/other/above gate.jpg`,
  },
  o2: {
    number: `o2`,
    label: `Other: Logo`,
    isFound: false,
    imagePath: `/other/logo.jpg`,
  },
  o3: {
    number: `o3`,
    label: `Other: Menu`,
    isFound: false,
    imagePath: `/other/menu 1.jpg`,
  },
  o4: {
    number: `o4`,
    label: `Other: Menu Card`,
    isFound: false,
    imagePath: `/other/menu card.jpg`,
  },
  o5: {
    number: `o5`,
    label: `Other: Chalk Board 1`,
    isFound: false,
    imagePath: `/other/chalk board 1.jpg`,
  },
  o6: {
    number: `o6`,
    label: `Other: Chalk Board 2`,
    isFound: false,
    imagePath: `/other/chalk board 2.jpg`,
  },
  o7: {
    number: `o7`,
    label: `Other: Chalk Board 3`,
    isFound: false,
    imagePath: `/other/chalk board 3.jpg`,
  },
  o8: {
    number: `o8`,
    label: `Other: Chalk Board 4`,
    isFound: false,
    imagePath: `/other/chalk board 4.jpg`,
  },
  o9: {
    number: `o9`,
    label: `Other: Garden Knight`,
    isFound: false,
    imagePath: `/other/garden knight.jpg`,
  },
  o10: {
    number: `o10`,
    label: `Other: Siege Engine`,
    isFound: false,
    imagePath: `/other/siege engine.jpg`,
  },
  o11: {
    number: `o11`,
    label: `Other: Boss Scavanger`,
    isFound: false,
    imagePath: `/other/boss scavanger.jpg`,
  },
  o12: {
    number: `o12`,
    label: `Other: The Librarian`,
    isFound: false,
    imagePath: `/other/librarian.jpg`,
  },
  t1: {
    number: `t1`,
    label: `Talk: Behind Trees`,
    isFound: false,
    imagePath: `/talk/behind trees combined.jpg`,
  },
  t2: {
    number: `t2`,
    label: `Talk: Broken Statue`,
    isFound: false,
    imagePath: `/talk/broken statue 1.jpg`,
  },
  t3: {
    number: `t3`,
    label: `Talk: Broken Teleporter`,
    isFound: false,
    imagePath: `/talk/broken teleporter.jpg`,
  },
  t4: {
    number: `t4`,
    label: `Talk: Candle`,
    isFound: false,
    imagePath: `/talk/candle combined.jpg`,
  },
  t5: {
    number: `t5`,
    label: `Talk: Fish`,
    isFound: false,
    imagePath: `/talk/fish combined.jpg`,
  },
  t6: {
    number: `t6`,
    label: `Talk: Fountain`,
    isFound: false,
    imagePath: `/talk/fountain.jpg`,
  },
  t7: {
    number: `t7`,
    label: `Talk: Fourth Key`,
    isFound: false,
    imagePath: `/talk/fourth key.jpg`,
  },
  t8: {
    number: `t8`,
    label: `Talk: Garden`,
    isFound: false,
    imagePath: `/talk/garden 1.jpg`,
  },
  t9: {
    number: `t9`,
    label: `Talk: Graveyard Entrance`,
    isFound: false,
    imagePath: `/talk/grave entrance combined.jpg`,
  },
  t10: {
    number: `t10`,
    label: `Talk: Graveyard`,
    isFound: false,
    imagePath: `/talk/Graveyard 1.jpg`,
  },
  t11: {
    number: `t11`,
    label: `Talk: Green Seal`,
    isFound: false,
    imagePath: `/talk/green seal.jpg`,
  },
  t12: {
    number: `t12`,
    label: `Talk: Incredible Treasure`,
    isFound: false,
    imagePath: `/talk/incredible treasure combined.jpg`,
  },
  t13: {
    number: `t13`,
    label: `Talk: Island`,
    isFound: false,
    imagePath: `/talk/island combined.jpg`,
  },
  t14: {
    number: `t14`,
    label: `Talk: Librarian`,
    isFound: false,
    imagePath: `/talk/libraryan combined.jpg`,
  },
  t15: {
    number: `t15`,
    label: `Talk: Looking`,
    isFound: false,
    imagePath: `/talk/looking.jpg`,
  },
  t16: {
    number: `t16`,
    label: `Talk: Mailbox`,
    isFound: false,
    imagePath: `/talk/Mailbox combined.jpg`,
  },
  t17: {
    number: `t17`,
    label: `Talk: Pose`,
    isFound: false,
    imagePath: `/talk/pose.jpg`,
  },
  t18: {
    number: `t18`,
    label: `Talk: Red Seal`,
    isFound: false,
    imagePath: `/talk/red seal.jpg`,
  },
  t19: {
    number: `t19`,
    label: `Talk: Seal Key`,
    isFound: false,
    imagePath: `/talk/seal down combined.jpg`,
  },
  t20: {
    number: `t20`,
    label: `Talk: Sitting`,
    isFound: false,
    imagePath: `/talk/sitting.jpg`,
  },
  t21: {
    number: `t21`,
    label: `Talk: Sleeping`,
    isFound: false,
    imagePath: `/talk/sleeping combined.jpg`,
  },
  t22: {
    number: `t22`,
    label: `Talk: Something Bad`,
    isFound: false,
    imagePath: `/talk/something bad.jpg`,
  },
  t23: {
    number: `t23`,
    label: `Talk: Statue`,
    isFound: false,
    imagePath: `/talk/statue.jpg`,
  },
  t24: {
    number: `t24`,
    label: `Talk: Storage`,
    isFound: false,
    imagePath: `/talk/storage.jpg`,
  },
  t25: {
    number: `t25`,
    label: `Talk: Well`,
    isFound: false,
    imagePath: `/talk/well combined.jpg`,
  },
  t26: {
    number: `t26`,
    label: `Talk: Windmill`,
    isFound: false,
    imagePath: `/talk/windmill combined.jpg`,
  },
}

export function updatePageInfoList(foundPages: Record<string, boolean>) {
  for (const pageInfoNumber in pageInfoList) {
    const pageInfo = pageInfoList[pageInfoNumber];
    pageInfo.isFound = foundPages[pageInfoNumber];
  }
  console.log("Synced found pages", foundPages);
  return pageInfoList
}